version: "2.2"
services:
  
  irisA:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: irisA
    command: --check-caps false
    image: workshop-sam-monitoring:iris
    ports:
      - 9191:52773
      - 9192:1972

  irisB:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: irisB
    command: --check-caps false
    image: workshop-sam-monitoring:iris
    ports:
      - 9291:52773
      - 9292:1972



